### ISSUE TITLE
no slot of name "reducedDim" for this object of class "PseudotimeOrdering"

### ISSUE THREAD

**Issue by PietroD** [HectorRDB/condimentsPaper#1]
Dear @HectorRDB ,

I encounter an error when executing the line below of the https://hectorrdb.github.io/condimentsPaper/articles/TCDD.html#session-info-1 vignette:

`pst <- data.frame(cells = rownames(sds@reducedDim),
                  pst = slingPseudotime(sds)[, 1])`

`Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'rownames': no slot of name "reducedDim" for this object of class "PseudotimeOrdering"`

**Comment by HectorRDB** [comment]
Hi @PietroD,
This error comes from the latest version of slingshot, which made a full overall of the underlying code. You will need to install slingshot from Bioc 3.12 in order for the vignette to run (and also the correct condiment version, there is a tagged release that should work). 
Best,

**Comment by HectorRDB** [comment]
Closing after more than a month of inactivity. Feel free to reopen if the issue persists.
