### ISSUE TITLE
Multi-condition analysis

### ISSUE THREAD

**Issue by dhivyaa-6** [HectorRDB/condimentsPaper#2]
I followed the analysis of the kras dataset and implementing the same for a multi-condition (5 conditions) trajectory inference. I have issues in the step 

     sds <- do.call(merge_sds, sdss)

Where I get the error Error in (function (..., mapping, condition_id = seq_len(ncol(mapping)),  : 
  Some lineages are not mapped

The same works well for the 2 conditions. Is there something am missing while analyzing 5 conditions at the same time? I also tried for 3 and did not work.

**Comment by HectorRDB** [comment]
Issue moved to https://github.com/HectorRDB/condiments/issues/3
